colorscheme desertex

# Help on everything
set global autoinfo command|onkey|normal

set global scrolloff 2,0
set global grepcmd 'ag -S --hidden --ignore=.git --ignore=.hg --ignore=.svn'
set global modelinefmt '%val{bufname} %val{cursor_line}:%val{cursor_char_column} [%opt{filetype}]'

map global normal <ret> jgh

hook global WinCreate .* %{

    # {}, <>, ...
    addhl show_matching

    # 1 lorem ipsum
    addhl number_lines -hlcursor -separator ' '
}
