# Help on everything
set global autoinfo command|onkey|normal
set global scrolloff 2,0

# Highlight paired chars ({}, <>, ...) in cyan bold
face MatchingChar cyan+b

hook global WinCreate .* %{

    # {}, <>, ...
    addhl show_matching

    # 1 lorem ipsum
    addhl number_lines -hlcursor -separator ' '
}
