colorscheme desertex

# Help on everything
set global autoinfo command|onkey|normal

set global scrolloff 2,0
set global grepcmd 'ag -S --hidden --ignore=.git --ignore=.hg --ignore=.svn'
set global modelinefmt '%val{bufname} %val{cursor_line}:%val{cursor_char_column} [%opt{filetype}]'

map global normal <ret> jgh

hook global WinCreate .* %{

    # auto cd to current file's working directory
    %sh{ bash -c '[[ $kak_buffile == */* ]] && echo cd "\"${kak_buffile%/*}\""' }

    # {}, <>, ...
    addhl show_matching

    # 1 lorem ipsum
    addhl number_lines -hlcursor -separator ' '

    map global normal <c-g> ':echo %val{buffile}<ret>'

    addhl dynregex '%reg{/}' 0:default,rgb:373b41
}

hook global WinDisplay .* %{

    %sh{ bash -c '[[ $kak_buffile == */* ]] && echo cd "\"${kak_buffile%/*}\""' }
}

# Local settings
%sh{
if [ -f "$XDG_CONFIG_HOME"/kak/extra.kak ]
then
    echo "source '$XDG_CONFIG_HOME/kak/extra.kak'"
fi
}
