#! /usr/bin/env zsh

fpath=($XDG_CONFIG_HOME/zsh/autoload/*(N/))
autoload start_ssh_agent pg

start_ssh_agent || exit 1

session=work

tmux new-session -d -s${session} -nIRC
tmux set-window-option -t${session}:IRC allow-rename off
tmux send-keys -t${session}:IRC 'weechat' C-m

# local
tmux new-window -t${session} -nlocal
tmux set-window-option -t${session}:local allow-rename off
tmux split-window -t${session}:local -h
tmux select-pane -t${session}:local -L

# remote
tmux new-window -t${session} -nremote
tmux set-window-option -t${session}:remote allow-rename off
tmux split-window -t${session}:remote -h
tmux select-pane -t${session}:remote -L

tmux attach-session -t${session}
