#! /usr/bin/env bash

if [[ $1 == -@(h|-h)* ]] || (($# < 1))
then
read -r -d $'\0' info << 'HELP'
Usage:
layout {host prefix} [number of hosts (>1, default: 3)] OR
       host1 host2 ...
HELP
   if (($#))
   then echo "$info"    ; exit 0
   else echo "$info" >&2; exit 1
   fi
fi

if (($# == 1)) || { (($# == 2)) && [[ $2 == [0-9]* ]]; }
then
   [[ $2 == [01] ]] && { echo "Abort. The second arg must be > 1" 1>&2; exit 2; }

   prefix="$1"
   nb_hosts="${2:-3}"

   tmux new-window -n "$prefix" "ssh ${prefix}1"

   for ((i = 2; i < nb_hosts + 1; i++))
   do
      tmux split-window -h "ssh ${prefix}$i"
      ((i < 4)) && continue
      tmux select-layout tiled >/dev/null
   done
else
   tmux new-window -n 'multi' "ssh $1"

   j=2
   for h in "${@:2}"
   do
      tmux split-window -h "ssh $h"
      ((j++ < 4)) && continue
      tmux select-layout tiled >/dev/null
   done
fi

if { [[ $nb_hosts ]] && ((nb_hosts < 4)); } || { [[ ! $nb_hosts ]] && (($# < 4)); }
then
   tmux select-layout even-horizontal >/dev/null
fi

tmux select-pane -t 1
tmux set-window-option synchronize-panes on >/dev/null
