#! /usr/bin/env zsh

session=work

tmux new-session -d -s${session} -nIRC
tmux set-option -t${session} -g automatic-rename off
tmux send-keys -t${session}:IRC 'weechat' C-m

# local
tmux new-window -t${session} -nlocal
tmux split-window -t${session}:local -h
tmux select-pane -t${session}:local -L

# remote
tmux new-window -t${session} -nremote
tmux split-window -t${session}:remote -h
tmux select-pane -t${session}:remote -L

tmux attach-session -t${session}
